// <auto-generated />
using System;
using CineShop.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineShop.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250912110340_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingZip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryZip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingAddress = "Storgatan 12",
                            BillingCity = "Stockholm",
                            BillingZip = "11122",
                            DeliveryAddress = "Storgatan 12",
                            DeliveryCity = "Stockholm",
                            DeliveryZip = "11122",
                            EmailAddress = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Andersson",
                            PhoneNo = "+46701234567"
                        },
                        new
                        {
                            Id = 2,
                            BillingAddress = "Kungsgatan 45",
                            BillingCity = "Göteborg",
                            BillingZip = "41115",
                            DeliveryAddress = "Kungsgatan 45",
                            DeliveryCity = "Göteborg",
                            DeliveryZip = "41115",
                            EmailAddress = "bjorn@example.com",
                            FirstName = "Björn",
                            LastName = "Bergström",
                            PhoneNo = "+46709876543"
                        },
                        new
                        {
                            Id = 3,
                            BillingAddress = "Lundavägen 8",
                            BillingCity = "Malmö",
                            BillingZip = "20520",
                            DeliveryAddress = "Lundavägen 8",
                            DeliveryCity = "Malmö",
                            DeliveryZip = "20520",
                            EmailAddress = "clara@example.com",
                            FirstName = "Clara",
                            LastName = "Carlsson",
                            PhoneNo = "+46705551234"
                        });
                });

            modelBuilder.Entity("CineShop.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Eva Lindström",
                            Genre = "Drama",
                            Image = "https://example.com/images/northern-light.jpg",
                            Price = 129.00m,
                            ReleaseYear = 2022,
                            Title = "The Northern Light"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Oskar Berg",
                            Genre = "Drama",
                            Image = "https://example.com/images/midnight-fjord.jpg",
                            Price = 149.50m,
                            ReleaseYear = 2023,
                            Title = "Midnight Fjord"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Karin Nyström",
                            Genre = "Drama",
                            Image = "https://example.com/images/echoes-lapland.jpg",
                            Price = 99.99m,
                            ReleaseYear = 2021,
                            Title = "Echoes of Lapland"
                        });
                });

            modelBuilder.Entity("CineShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CineShop.Models.OrderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("Order Row");
                });

            modelBuilder.Entity("CineShop.Models.Order", b =>
                {
                    b.HasOne("CineShop.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CineShop.Models.OrderRow", b =>
                {
                    b.HasOne("CineShop.Models.Movie", "Movie")
                        .WithMany("OrderRows")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineShop.Models.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CineShop.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CineShop.Models.Movie", b =>
                {
                    b.Navigation("OrderRows");
                });

            modelBuilder.Entity("CineShop.Models.Order", b =>
                {
                    b.Navigation("OrderRows");
                });
#pragma warning restore 612, 618
        }
    }
}
